# Generated by Django 4.0.4 on 2022-04-17 15:34

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighbourHoodApp', '0003_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('post_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('content', models.TextField()),
                ('posted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('neiborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourHoodApp.neighbourhood')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='neighbourHoodApp.profile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
