# Generated by Django 4.0.4 on 2022-04-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourHoodApp', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neiborhood',
            new_name='neighborhood',
        ),
    ]
